services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_URL: ${PG_URL_DOCKER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm run db:create && npm run db:seed && npm run dev"
volumes:
  db_data:
